/*
 * Copyright (c) 2026. caoccao.com Sam Cao
 * All rights reserved.
 *
 * Subset of common ISO 639-2/B/T language codes.
 * Falls back to the raw code when no entry matches.
 */

pub fn language_name(code: &str) -> &'static str {
    let code = code.trim_end_matches('\0').to_ascii_lowercase();
    match code.as_str() {
        "abk" => "Abkhazian",
        "afr" => "Afrikaans",
        "alb" | "sqi" => "Albanian",
        "amh" => "Amharic",
        "ara" => "Arabic",
        "arm" | "hye" => "Armenian",
        "asm" => "Assamese",
        "aze" => "Azerbaijani",
        "ben" => "Bengali",
        "bos" => "Bosnian",
        "bul" => "Bulgarian",
        "bur" | "mya" => "Burmese",
        "cat" => "Catalan",
        "chi" | "zho" => "Chinese",
        "hrv" => "Croatian",
        "cze" | "ces" => "Czech",
        "dan" => "Danish",
        "dut" | "nld" => "Dutch",
        "eng" => "English",
        "est" => "Estonian",
        "fao" => "Faroese",
        "fij" => "Fijian",
        "fin" => "Finnish",
        "fre" | "fra" => "French",
        "geo" | "kat" => "Georgian",
        "ger" | "deu" => "German",
        "gre" | "ell" => "Greek",
        "guj" => "Gujarati",
        "hau" => "Hausa",
        "heb" => "Hebrew",
        "hin" => "Hindi",
        "hun" => "Hungarian",
        "ice" | "isl" => "Icelandic",
        "ind" => "Indonesian",
        "gle" => "Irish",
        "ita" => "Italian",
        "jpn" => "Japanese",
        "jav" => "Javanese",
        "kan" => "Kannada",
        "kaz" => "Kazakh",
        "khm" => "Khmer",
        "kor" => "Korean",
        "kur" => "Kurdish",
        "lao" => "Lao",
        "lat" => "Latin",
        "lav" => "Latvian",
        "lit" => "Lithuanian",
        "ltz" => "Luxembourgish",
        "mac" | "mkd" => "Macedonian",
        "may" | "msa" => "Malay",
        "mal" => "Malayalam",
        "mlt" => "Maltese",
        "mri" => "Maori",
        "mar" => "Marathi",
        "mon" => "Mongolian",
        "nep" => "Nepali",
        "nor" => "Norwegian",
        "nob" => "Norwegian Bokmål",
        "nno" => "Norwegian Nynorsk",
        "pan" => "Panjabi",
        "per" | "fas" => "Persian",
        "pol" => "Polish",
        "por" => "Portuguese",
        "que" => "Quechua",
        "rum" | "ron" => "Romanian",
        "rus" => "Russian",
        "san" => "Sanskrit",
        "srp" => "Serbian",
        "sin" => "Sinhala",
        "slo" | "slk" => "Slovak",
        "slv" => "Slovenian",
        "som" => "Somali",
        "spa" => "Spanish",
        "swa" => "Swahili",
        "swe" => "Swedish",
        "tgl" => "Tagalog",
        "tgk" => "Tajik",
        "tam" => "Tamil",
        "tel" => "Telugu",
        "tha" => "Thai",
        "tib" | "bod" => "Tibetan",
        "tur" => "Turkish",
        "tuk" => "Turkmen",
        "ukr" => "Ukrainian",
        "urd" => "Urdu",
        "uzb" => "Uzbek",
        "vie" => "Vietnamese",
        "wel" | "cym" => "Welsh",
        "yid" => "Yiddish",
        "yor" => "Yoruba",
        "zul" => "Zulu",
        "" => "",
        _ => "",
    }
}
