/*
 * Copyright (c) 2026. caoccao.com Sam Cao
 * All rights reserved.
 *
 * ISO 639-2 language-code lookup ported verbatim from BDInfo's `LanguageCodes.cs`.
 * The `LANGUAGE_CODES` table mirrors BDInfo's `GetName` switch one entry per
 * `case`, so parity is preserved by construction. Unknown codes fall back to the
 * raw (trimmed) code, matching BDInfo's `default: return code;` behavior.
 */

/// (code, English name) pairs mirroring BDInfo's `LanguageCodes.GetName` switch.
pub const LANGUAGE_CODES: &[(&str, &str)] = &[
    ("abk", "Abkhazian"),
    ("ace", "Achinese"),
    ("ach", "Acoli"),
    ("ada", "Adangme"),
    ("aar", "Afar"),
    ("afh", "Afrihili"),
    ("afr", "Afrikaans"),
    ("afa", "Afro-Asiatic (Other)"),
    ("aka", "Akan"),
    ("akk", "Akkadian"),
    ("alb", "Albanian"),
    ("sqi", "Albanian"),
    ("ale", "Aleut"),
    ("alg", "Algonquian languages"),
    ("tut", "Altaic (Other)"),
    ("amh", "Amharic"),
    ("apa", "Apache languages"),
    ("ara", "Arabic"),
    ("arc", "Aramaic"),
    ("arp", "Arapaho"),
    ("arn", "Araucanian"),
    ("arw", "Arawak"),
    ("arm", "Armenian"),
    ("hye", "Armenian"),
    ("art", "Artificial (Other)"),
    ("asm", "Assamese"),
    ("ath", "Athapascan languages"),
    ("aus", "Australian languages"),
    ("map", "Austronesian (Other)"),
    ("ava", "Avaric"),
    ("ave", "Avestan"),
    ("awa", "Awadhi"),
    ("aym", "Aymara"),
    ("aze", "Azerbaijani"),
    ("ban", "Balinese"),
    ("bat", "Baltic (Other)"),
    ("bal", "Baluchi"),
    ("bam", "Bambara"),
    ("bai", "Bamileke languages"),
    ("bad", "Banda"),
    ("bnt", "Bantu (Other)"),
    ("bas", "Basa"),
    ("bak", "Bashkir"),
    ("baq", "Basque"),
    ("eus", "Basque"),
    ("btk", "Batak (Indonesia)"),
    ("bej", "Beja"),
    ("bel", "Belarusian"),
    ("bem", "Bemba"),
    ("ben", "Bengali"),
    ("ber", "Berber (Other)"),
    ("bho", "Bhojpuri"),
    ("bih", "Bihari"),
    ("bik", "Bikol"),
    ("bin", "Bini"),
    ("bis", "Bislama"),
    ("bos", "Bosnian"),
    ("bra", "Braj"),
    ("bre", "Breton"),
    ("bug", "Buginese"),
    ("bul", "Bulgarian"),
    ("bua", "Buriat"),
    ("bur", "Burmese"),
    ("mya", "Burmese"),
    ("cad", "Caddo"),
    ("car", "Carib"),
    ("cat", "Catalan"),
    ("cau", "Caucasian (Other)"),
    ("ceb", "Cebuano"),
    ("cel", "Celtic (Other)"),
    ("cai", "Central American Indian (Other)"),
    ("chg", "Chagatai"),
    ("cmc", "Chamic languages"),
    ("cha", "Chamorro"),
    ("che", "Chechen"),
    ("chr", "Cherokee"),
    ("chy", "Cheyenne"),
    ("chb", "Chibcha"),
    ("chi", "Chinese"),
    ("zho", "Chinese"),
    ("chn", "Chinook jargon"),
    ("chp", "Chipewyan"),
    ("cho", "Choctaw"),
    ("chu", "Church Slavic"),
    ("chk", "Chuukese"),
    ("chv", "Chuvash"),
    ("cop", "Coptic"),
    ("cor", "Cornish"),
    ("cos", "Corsican"),
    ("cre", "Cree"),
    ("mus", "Creek"),
    ("crp", "Creoles and pidgins (Other)"),
    ("cpe", "Creoles and pidgins,"),
    ("cpf", "Creoles and pidgins,"),
    ("cpp", "Creoles and pidgins,"),
    ("scr", "Croatian"),
    ("hrv", "Croatian"),
    ("cus", "Cushitic (Other)"),
    ("cze", "Czech"),
    ("ces", "Czech"),
    ("dak", "Dakota"),
    ("dan", "Danish"),
    ("day", "Dayak"),
    ("del", "Delaware"),
    ("din", "Dinka"),
    ("div", "Divehi"),
    ("doi", "Dogri"),
    ("dgr", "Dogrib"),
    ("dra", "Dravidian (Other)"),
    ("dua", "Duala"),
    ("dut", "Dutch"),
    ("nld", "Dutch"),
    ("dum", "Dutch, Middle (ca. 1050-1350)"),
    ("dyu", "Dyula"),
    ("dzo", "Dzongkha"),
    ("efi", "Efik"),
    ("egy", "Egyptian (Ancient)"),
    ("eka", "Ekajuk"),
    ("elx", "Elamite"),
    ("eng", "English"),
    ("enm", "English, Middle (1100-1500)"),
    ("ang", "English, Old (ca.450-1100)"),
    ("epo", "Esperanto"),
    ("est", "Estonian"),
    ("ewe", "Ewe"),
    ("ewo", "Ewondo"),
    ("fan", "Fang"),
    ("fat", "Fanti"),
    ("fao", "Faroese"),
    ("fij", "Fijian"),
    ("fin", "Finnish"),
    ("fiu", "Finno-Ugrian (Other)"),
    ("fon", "Fon"),
    ("fre", "French"),
    ("fra", "French"),
    ("frm", "French, Middle (ca.1400-1600)"),
    ("fro", "French, Old (842-ca.1400)"),
    ("fry", "Frisian"),
    ("fur", "Friulian"),
    ("ful", "Fulah"),
    ("gaa", "Ga"),
    ("glg", "Gallegan"),
    ("lug", "Ganda"),
    ("gay", "Gayo"),
    ("gba", "Gbaya"),
    ("gez", "Geez"),
    ("geo", "Georgian"),
    ("kat", "Georgian"),
    ("ger", "German"),
    ("deu", "German"),
    ("nds", "Saxon"),
    ("gmh", "German, Middle High (ca.1050-1500)"),
    ("goh", "German, Old High (ca.750-1050)"),
    ("gem", "Germanic (Other)"),
    ("gil", "Gilbertese"),
    ("gon", "Gondi"),
    ("gor", "Gorontalo"),
    ("got", "Gothic"),
    ("grb", "Grebo"),
    ("grc", "Greek, Ancient (to 1453)"),
    ("gre", "Greek"),
    ("ell", "Greek"),
    ("grn", "Guarani"),
    ("guj", "Gujarati"),
    ("gwi", "Gwich´in"),
    ("hai", "Haida"),
    ("hau", "Hausa"),
    ("haw", "Hawaiian"),
    ("heb", "Hebrew"),
    ("her", "Herero"),
    ("hil", "Hiligaynon"),
    ("him", "Himachali"),
    ("hin", "Hindi"),
    ("hmo", "Hiri Motu"),
    ("hit", "Hittite"),
    ("hmn", "Hmong"),
    ("hun", "Hungarian"),
    ("hup", "Hupa"),
    ("iba", "Iban"),
    ("ice", "Icelandic"),
    ("isl", "Icelandic"),
    ("ibo", "Igbo"),
    ("ijo", "Ijo"),
    ("ilo", "Iloko"),
    ("inc", "Indic (Other)"),
    ("ine", "Indo-European (Other)"),
    ("ind", "Indonesian"),
    ("ina", "Interlingua (International"),
    ("ile", "Interlingue"),
    ("iku", "Inuktitut"),
    ("ipk", "Inupiaq"),
    ("ira", "Iranian (Other)"),
    ("gle", "Irish"),
    ("mga", "Irish, Middle (900-1200)"),
    ("sga", "Irish, Old (to 900)"),
    ("iro", "Iroquoian languages"),
    ("ita", "Italian"),
    ("jpn", "Japanese"),
    ("jav", "Javanese"),
    ("jrb", "Judeo-Arabic"),
    ("jpr", "Judeo-Persian"),
    ("kab", "Kabyle"),
    ("kac", "Kachin"),
    ("kal", "Kalaallisut"),
    ("kam", "Kamba"),
    ("kan", "Kannada"),
    ("kau", "Kanuri"),
    ("kaa", "Kara-Kalpak"),
    ("kar", "Karen"),
    ("kas", "Kashmiri"),
    ("kaw", "Kawi"),
    ("kaz", "Kazakh"),
    ("kha", "Khasi"),
    ("khm", "Khmer"),
    ("khi", "Khoisan (Other)"),
    ("kho", "Khotanese"),
    ("kik", "Kikuyu"),
    ("kmb", "Kimbundu"),
    ("kin", "Kinyarwanda"),
    ("kir", "Kirghiz"),
    ("kom", "Komi"),
    ("kon", "Kongo"),
    ("kok", "Konkani"),
    ("kor", "Korean"),
    ("kos", "Kosraean"),
    ("kpe", "Kpelle"),
    ("kro", "Kru"),
    ("kua", "Kuanyama"),
    ("kum", "Kumyk"),
    ("kur", "Kurdish"),
    ("kru", "Kurukh"),
    ("kut", "Kutenai"),
    ("lad", "Ladino"),
    ("lah", "Lahnda"),
    ("lam", "Lamba"),
    ("lao", "Lao"),
    ("lat", "Latin"),
    ("lav", "Latvian"),
    ("ltz", "Letzeburgesch"),
    ("lez", "Lezghian"),
    ("lin", "Lingala"),
    ("lit", "Lithuanian"),
    ("loz", "Lozi"),
    ("lub", "Luba-Katanga"),
    ("lua", "Luba-Lulua"),
    ("lui", "Luiseno"),
    ("lun", "Lunda"),
    ("luo", "Luo (Kenya and Tanzania)"),
    ("lus", "Lushai"),
    ("mac", "Macedonian"),
    ("mkd", "Macedonian"),
    ("mad", "Madurese"),
    ("mag", "Magahi"),
    ("mai", "Maithili"),
    ("mak", "Makasar"),
    ("mlg", "Malagasy"),
    ("may", "Malay"),
    ("msa", "Malay"),
    ("mal", "Malayalam"),
    ("mlt", "Maltese"),
    ("mnc", "Manchu"),
    ("mdr", "Mandar"),
    ("man", "Mandingo"),
    ("mni", "Manipuri"),
    ("mno", "Manobo languages"),
    ("glv", "Manx"),
    ("mao", "Maori"),
    ("mri", "Maori"),
    ("mar", "Marathi"),
    ("chm", "Mari"),
    ("mah", "Marshall"),
    ("mwr", "Marwari"),
    ("mas", "Masai"),
    ("myn", "Mayan languages"),
    ("men", "Mende"),
    ("mic", "Micmac"),
    ("min", "Minangkabau"),
    ("mis", "Miscellaneous languages"),
    ("moh", "Mohawk"),
    ("mol", "Moldavian"),
    ("mkh", "Mon-Khmer (Other)"),
    ("lol", "Mongo"),
    ("mon", "Mongolian"),
    ("mos", "Mossi"),
    ("mul", "Multiple languages"),
    ("mun", "Munda languages"),
    ("nah", "Nahuatl"),
    ("nau", "Nauru"),
    ("nav", "Navajo"),
    ("nde", "Ndebele, North"),
    ("nbl", "Ndebele, South"),
    ("ndo", "Ndonga"),
    ("nep", "Nepali"),
    ("new", "Newari"),
    ("nia", "Nias"),
    ("nic", "Niger-Kordofanian (Other)"),
    ("ssa", "Nilo-Saharan (Other)"),
    ("niu", "Niuean"),
    ("non", "Norse, Old"),
    ("nai", "North American Indian (Other)"),
    ("sme", "Northern Sami"),
    ("nor", "Norwegian"),
    ("nob", "Norwegian Bokmål"),
    ("nno", "Norwegian Nynorsk"),
    ("nub", "Nubian languages"),
    ("nym", "Nyamwezi"),
    ("nya", "Nyanja"),
    ("nyn", "Nyankole"),
    ("nyo", "Nyoro"),
    ("nzi", "Nzima"),
    ("oci", "Occitan"),
    ("oji", "Ojibwa"),
    ("ori", "Oriya"),
    ("orm", "Oromo"),
    ("osa", "Osage"),
    ("oss", "Ossetian"),
    ("oto", "Otomian languages"),
    ("pal", "Pahlavi"),
    ("pau", "Palauan"),
    ("pli", "Pali"),
    ("pam", "Pampanga"),
    ("pag", "Pangasinan"),
    ("pan", "Panjabi"),
    ("pap", "Papiamento"),
    ("paa", "Papuan (Other)"),
    ("per", "Persian"),
    ("fas", "Persian"),
    ("peo", "Persian, Old (ca.600-400 B.C.)"),
    ("phi", "Philippine (Other)"),
    ("phn", "Phoenician"),
    ("pon", "Pohnpeian"),
    ("pol", "Polish"),
    ("por", "Portuguese"),
    ("pra", "Prakrit languages"),
    ("pro", "Provençal"),
    ("pus", "Pushto"),
    ("que", "Quechua"),
    ("roh", "Raeto-Romance"),
    ("raj", "Rajasthani"),
    ("rap", "Rapanui"),
    ("rar", "Rarotongan"),
    ("roa", "Romance (Other)"),
    ("rum", "Romanian"),
    ("ron", "Romanian"),
    ("rom", "Romany"),
    ("run", "Rundi"),
    ("rus", "Russian"),
    ("sal", "Salishan languages"),
    ("sam", "Samaritan Aramaic"),
    ("smi", "Sami languages (Other)"),
    ("smo", "Samoan"),
    ("sad", "Sandawe"),
    ("sag", "Sango"),
    ("san", "Sanskrit"),
    ("sat", "Santali"),
    ("srd", "Sardinian"),
    ("sas", "Sasak"),
    ("sco", "Scots"),
    ("gla", "Gaelic"),
    ("sel", "Selkup"),
    ("sem", "Semitic (Other)"),
    ("scc", "Serbian"),
    ("srp", "Serbian"),
    ("srr", "Serer"),
    ("shn", "Shan"),
    ("sna", "Shona"),
    ("sid", "Sidamo"),
    ("sgn", "Sign languages"),
    ("bla", "Siksika"),
    ("snd", "Sindhi"),
    ("sin", "Sinhalese"),
    ("sit", "Sino-Tibetan (Other)"),
    ("sio", "Siouan languages"),
    ("den", "Slave (Athapascan)"),
    ("sla", "Slavic (Other)"),
    ("slo", "Slovak"),
    ("slk", "Slovak"),
    ("slv", "Slovenian"),
    ("sog", "Sogdian"),
    ("som", "Somali"),
    ("son", "Songhai"),
    ("snk", "Soninke"),
    ("wen", "Sorbian languages"),
    ("nso", "Sotho, Northern"),
    ("sot", "Sotho, Southern"),
    ("sai", "South American Indian (Other)"),
    ("spa", "Spanish"),
    ("suk", "Sukuma"),
    ("sux", "Sumerian"),
    ("sun", "Sundanese"),
    ("sus", "Susu"),
    ("swa", "Swahili"),
    ("ssw", "Swati"),
    ("swe", "Swedish"),
    ("syr", "Syriac"),
    ("tgl", "Tagalog"),
    ("tah", "Tahitian"),
    ("tai", "Tai (Other)"),
    ("tgk", "Tajik"),
    ("tmh", "Tamashek"),
    ("tam", "Tamil"),
    ("tat", "Tatar"),
    ("tel", "Telugu"),
    ("ter", "Tereno"),
    ("tet", "Tetum"),
    ("tha", "Thai"),
    ("tib", "Tibetan"),
    ("bod", "Tibetan"),
    ("tig", "Tigre"),
    ("tir", "Tigrinya"),
    ("tem", "Timne"),
    ("tiv", "Tiv"),
    ("tli", "Tlingit"),
    ("tpi", "Tok Pisin"),
    ("tkl", "Tokelau"),
    ("tog", "Tonga (Nyasa)"),
    ("ton", "Tonga (Tonga Islands)"),
    ("tsi", "Tsimshian"),
    ("tso", "Tsonga"),
    ("tsn", "Tswana"),
    ("tum", "Tumbuka"),
    ("tur", "Turkish"),
    ("ota", "Turkish, Ottoman (1500-1928)"),
    ("tuk", "Turkmen"),
    ("tvl", "Tuvalu"),
    ("tyv", "Tuvinian"),
    ("twi", "Twi"),
    ("uga", "Ugaritic"),
    ("uig", "Uighur"),
    ("ukr", "Ukrainian"),
    ("umb", "Umbundu"),
    ("und", "Undetermined"),
    ("urd", "Urdu"),
    ("uzb", "Uzbek"),
    ("vai", "Vai"),
    ("ven", "Venda"),
    ("vie", "Vietnamese"),
    ("vol", "Volapük"),
    ("vot", "Votic"),
    ("wak", "Wakashan languages"),
    ("wal", "Walamo"),
    ("war", "Waray"),
    ("was", "Washo"),
    ("wel", "Welsh"),
    ("cym", "Welsh"),
    ("wol", "Wolof"),
    ("xho", "Xhosa"),
    ("sah", "Yakut"),
    ("yao", "Yao"),
    ("yap", "Yapese"),
    ("yid", "Yiddish"),
    ("yor", "Yoruba"),
    ("ypk", "Yupik languages"),
    ("znd", "Zande"),
    ("zap", "Zapotec"),
    ("zen", "Zenaga"),
    ("zha", "Zhuang"),
    ("zul", "Zulu"),
    ("zun", "Zuni"),
];

/// Returns the English language name for a Blu-ray three-letter language code.
///
/// Trailing NULs are trimmed and the code is lowercased before lookup. Unknown
/// or empty codes fall back to the trimmed input, matching BDInfo.
pub fn language_name(code: &str) -> String {
    let trimmed = code.trim_end_matches('\0');
    let lower = trimmed.to_ascii_lowercase();
    for (key, name) in LANGUAGE_CODES {
        if *key == lower {
            return (*name).to_string();
        }
    }
    trimmed.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_table_entry_resolves_to_its_name() {
        // Parity-by-construction: each BDInfo `case` maps to its name.
        for (code, name) in LANGUAGE_CODES {
            assert_eq!(language_name(code), *name, "code {code}");
        }
    }

    #[test]
    fn table_has_full_bdinfo_coverage() {
        // BDInfo's GetName switch has 459 cases.
        assert_eq!(LANGUAGE_CODES.len(), 459);
    }

    #[test]
    fn table_keys_are_unique() {
        let mut keys: Vec<&str> = LANGUAGE_CODES.iter().map(|(k, _)| *k).collect();
        keys.sort_unstable();
        let len = keys.len();
        keys.dedup();
        assert_eq!(keys.len(), len, "duplicate language codes present");
    }

    #[test]
    fn common_codes_match_bdinfo() {
        assert_eq!(language_name("eng"), "English");
        assert_eq!(language_name("jpn"), "Japanese");
        assert_eq!(language_name("zho"), "Chinese");
        assert_eq!(language_name("chi"), "Chinese");
        assert_eq!(language_name("fre"), "French");
        assert_eq!(language_name("fra"), "French");
    }

    #[test]
    fn iso_639_2_t_aliases_match_b_variants() {
        // Bibliographic (B) and terminologic (T) codes resolve to the same name.
        assert_eq!(language_name("ger"), language_name("deu"));
        assert_eq!(language_name("dut"), language_name("nld"));
        assert_eq!(language_name("cze"), language_name("ces"));
        assert_eq!(language_name("gre"), language_name("ell"));
        assert_eq!(language_name("ice"), language_name("isl"));
    }

    #[test]
    fn non_ascii_label_is_well_formed() {
        // The Norwegian Bokmål label must be valid UTF-8 (not mojibake).
        assert_eq!(language_name("nob"), "Norwegian Bokmål");
    }

    #[test]
    fn unknown_code_falls_back_to_raw_code() {
        // Matches BDInfo's `default: return code;`.
        assert_eq!(language_name("xyz"), "xyz");
        assert_eq!(language_name("qqq"), "qqq");
    }

    #[test]
    fn trailing_nuls_are_trimmed() {
        assert_eq!(language_name("eng\0"), "English");
        assert_eq!(language_name("eng\0\0"), "English");
        // Fallback also trims NULs before returning the raw code.
        assert_eq!(language_name("zz\0"), "zz");
    }

    #[test]
    fn lookup_is_case_insensitive() {
        assert_eq!(language_name("ENG"), "English");
        assert_eq!(language_name("Eng"), "English");
    }

    #[test]
    fn empty_code_returns_empty() {
        assert_eq!(language_name(""), "");
        assert_eq!(language_name("\0"), "");
    }
}
